--Conectarse a client Postgres
psql -U postgres

--Crear base de dades institut
CREATE DATABASE institut;

--Crear usuari institut i permisos
CREATE USER institut WITH SUPERUSER CREATEROLE ENCRYPTED PASSWORD 'institut';
ALTER DATABASE institut OWNER TO institut;
GRANT ALL PRIVILEGES ON DATABASE institut TO institut;

--Sortir del client
\q

--Connectarse a la base de dades institut amb el seu usuari
psql -U institut -W -d institut

--Creacio taules
CREATE TABLE IF NOT EXISTS PERSONA(
    DNI VARCHAR(9) NOT NULL,
    nom VARCHAR(50) NOT NULL,
    primerCog VARCHAR(50) NOT NULL,
    segonCog VARCHAR(50) NOT NULL,
    adreca VARCHAR(100),
    tlf NUMERIC(10),
    CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
    CONSTRAINT CK_NOM_MAJUS CHECK (nom = UPPER(nom)),
    CONSTRAINT CK_PRIMERCOG_MAJUS CHECK (nom = UPPER(primerCog)),
    CONSTRAINT CK_SEGONCOG_MAJUS CHECK (nom = UPPER(segonCog))
);

CREATE TABLE IF NOT EXISTS PROFESSOR (
    DNI VARCHAR(9) NOT NULL,
    especialitat VARCHAR(80) NOT NULL,
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (DNI),
    CONSTRAINT FK_PROFESSOR_PERSONA_DNI FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE IF NOT EXISTS ALUMNE (
    DNI VARCHAR(9) NOT NULL,
    dataNaix DATE NOT NULL,
    DNI_DELEGAT VARCHAR(9) NOT NULL,
    CONSTRAINT PK_ALUMNE PRIMARY KEY (DNI),
    CONSTRAINT FK_ALUMNE_PERSONA_DNI FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
    CONSTRAINT FK_ALUMNE_DELEGAT_DNI FOREIGN KEY (DNI_DELEGAT) REFERENCES ALUMNE(DNI)
);

CREATE TABLE IF NOT EXISTS AULA (
    numAula INTEGER NOT NULL,
    m2 INTEGER DEFAULT 20 NOT NULL,
    CONSTRAINT PK_AULA PRIMARY KEY (numAula),
    CONSTRAINT CK_M2_POS CHECK (m2>0),
    CONSTRAINT CK_M2_VALUES CHECK (m2 IN (20, 25, 30, 35, 40))
);

CREATE TABLE IF NOT EXISTS MODUL (
    codiModul INTEGER NOT NULL,
    nom VARCHAR(50) NOT NULL,
    numAula INTEGER NOT NULL,
    CONSTRAINT PK_MODUL PRIMARY KEY (codiModul),
    CONSTRAINT FK_MODUL_AULA_numAula FOREIGN KEY (numAula) REFERENCES AULA(numAula)
);

CREATE TABLE IF NOT EXISTS ASSIGNATURA (
    codiAssig INTEGER NOT NULL,
    nom VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ASSIGNATURA PRIMARY KEY (codiAssig)
);

CREATE TABLE IF NOT EXISTS pertany (
    codiModul INTEGER NOT NULL,
    codiAssig INTEGER NOT NULL,
    CONSTRAINT PK_PERTANY PRIMARY KEY (codiModul, codiAssig),
    CONSTRAINT FK_PERTANY_MODUL_codiModul FOREIGN KEY (codiModul) REFERENCES MODUL(codiModul),
    CONSTRAINT FK_PERTANY_ASSIGNATURA_codiAssig FOREIGN KEY (codiAssig) REFERENCES ASSIGNATURA(codiAssig)
);

CREATE TABLE IF NOT EXISTS ensenya (
    codiAssig INTEGER NOT NULL,
    DNIProfessor VARCHAR(9) NOT NULL,
    CONSTRAINT PK_ENSENYA PRIMARY KEY (codiAssig, DNIProfessor),
    CONSTRAINT FK_PERTANY_ASSIGNATURA_codiAssig FOREIGN KEY (codiAssig) REFERENCES ASSIGNATURA(codiAssig),
    CONSTRAINT FK_PERTANY_PROFESSOR_DNIProfessor FOREIGN KEY DNIProfessor REFERENCES PROFESSOR(DNI)
);

CREATE TABLE IF NOT EXISTS estudia (
    codiAssig INTEGER NOT NULL,
    DNIAlumne VARCHAR(9) NOT NULL,
    CONSTRAINT PK_ESTUDIA PRIMARY KEY (codiAssig, DNIAlumne),
    CONSTRAINT FK_PERTANY_ASSIGNATURA_codiAssig FOREIGN KEY (codiAssig) REFERENCES ASSIGNATURA(codiAssig),
    CONSTRAINT FK_PERTANY_PROFESSOR_DNIAlumne FOREIGN KEY (DNIAlumne) REFERENCES ALUMNE(DNI)
);
