CREATE TABLE IF NOT EXISTS FABRICANT (
    COD_FABRICANT NUMERIC(3) NOT NULL,
    NOM VARCHAR(15),
    PAIS VARCHAR(15),
    CONSTRAINT CH_NOM CHECK (NOM = UPPER(NOM)), --el camp nom ha de ser en upper (majus)
    CONSTRAINT CH_PAIS CHECK (PAIS = UPPER(PAIS)),
    CONSTRAINT PK_FABRICANT PRIMARY KEY (COD_FABRICANT)
);

CREATE TABLE IF NOT EXISTS ARTICLE (
    COD_ARTICLE VARCHAR(20) NOT NULL,
    COD_FABRICANT NUMERIC(3) NOT NULL,
    PES NUMERIC(3) NOT NULL,
    CATEGORIA VARCHAR(10) NOT NULL,
    PREU_VENDA DECIMAL(6,2),
    PREU_COST DECIMAL(6,2),
    STOCK NUMERIC(5),
    CONSTRAINT CH_PREU_VENDA CHECK (PREU_VENDA > 0),
    CONSTRAINT CH_PREU_COST CHECK (PREU_COST > 0),
    CONSTRAINT CH_PES CHECK (PES > 0),
    CONSTRAINT CH_CATEGORIA CHECK (CATEGORIA IN('Primera', 'Segona', 'Tercera')),
    CONSTRAINT PK_ARTICLE PRIMARY KEY (COD_ARTICLE, COD_FABRICANT, PES, CATEGORIA),
    CONSTRAINT FK_ARTICLE_FABRICANT FOREIGN KEY (COD_FABRICANT) REFERENCES FABRICANT(COD_FABRICANT)
);

