/*EA2 - Exercicis */
db.students.find({gender: "H"})
db.students.find({gender: "M"})
db.students.find({birth_year: 1993})
db.students.find({birth_year: 1993, gender: 'H'})
db.students.find({birth_year: {$gte: 1990, $lte: 1999}})
db.students.find({birth_year: {$lt: 1990}, gender: 'H'})
db.students.find({birth_year: {$lt: 1990}, gender: 'M'})
db.students.find({birth_year: {$gte: 1980, $lte: 1989}, gender: 'M'})
db.students.find({birth_year: {$gte: 1980, $lte: 1989}, gender: 'H'})
db.students.find({birth_year: {$gte: 1980, $lte: 1989}, gender: 'M'})
db.students.find({birth_year: {$ne: 1985}})
db.students.find({birth_year: {$in: [1970, 1980, 1990]}})
db.students.find({birth_year: {$nin: [1970, 1980, 1990]}})
db.students.find({birth_year: {$mod: [2, 0]}})
db.students.find({birth_year: {$mod: [10, 0]}})
db.students.find({phone_aux: {$ne: ''}})
db.students.find({lastname2: ''})
db.students.find({lastname2: '', phone_aux: {$ne: ''}})
db.students.find({email: {$regex: /\.net$/}})
db.students.find({firstname: {$regex: /^[aeiouàèòíúë]/i }})
db.students.find({firstname: {$regex: /^.{14,}$/ }})
db.students.find({firstname: { $regex: /([aeiou].*){4,}/i }})
db.students.find({dni: { $regex: /^[A-Z]/i }})
db.students.find({dni: { $regex: /^[A-Z].*[A-Z]$/i }})
db.students.find({phone: { $regex: /^622/ }})